### ISSUE TITLE
There is no existing username check when a user is created.

### ISSUE THREAD

**Issue by mattoehrlein** [elplatt/seltzer#195]
When a new user is created, a check should be done to make sure that the new username does not already exist in the database. If it does, the new user should be prompted to choose a different username.

**Comment by chris18890** [comment]
Closing this, as there has been a test since 0.3.0

Currently lines 411-436 of /crm/modules/member/command.inc.php

    // Find username or create a new one
    $username = $row['username'];
    $n = 0;
    while (empty($username) && $n < 100) {
        
        // Construct test username
        $test_username = strtolower($row['firstname']{0} . $row['lastname']);
        if ($n > 0) {
            $test_username .= $n;
        }
            
        // Check whether username is taken
        $esc_test_name = mysqli_real_escape_string($db_connect, $test_username);
        $sql = "SELECT * FROM `user` WHERE `username`='$esc_test_name'";
        $res = mysqli_query($db_connect, $sql);
        if (!$res) crm_error(mysqli_error($res));
        $user_row = mysqli_fetch_assoc($res);
        if (!$user_row) {
            $username = $test_username;
        }
        $n++;
    }
    if (empty($username)) {
        error_register('Please specify a username');
        return crm_url('members&tab=import');
    }

**Comment by chris18890** [comment]
re-opening this as I've since discovered that the code doesn't work
