### ISSUE TITLE
payment module freaks out unless both credit and debit fields are supplied and not empty.

### ISSUE THREAD

**Issue by davidbuzz** [elplatt/seltzer#211]
without this, you can't add a payment of type credit, as it complains that the debit field is '', and that's not allowed in the database.  ( and vice-versa ) 

diff --git a/crm/modules/payment/payment.inc.php b/crm/modules/payment/payment.inc.php
index a85bc1c..fbb1db4 100644
--- a/crm/modules/payment/payment.inc.php
+++ b/crm/modules/payment/payment.inc.php
@@ -404,6 +404,12 @@ function payment_save ($payment) {
     $esc_method = mysql_real_escape_string($payment['method']);
     $esc_confirmation = mysql_real_escape_string($payment['confirmation']);
     $esc_notes = mysql_real_escape_string($payment['notes']);
+
-    // allow the credit field to be zero ( typically when the debit field is used)
-    if ( $esc_credit == '' ) { $esc_debit = 0; }
-    // same, same.
-    if ( $esc_debit == '' ) { $esc_debit = 0; }
  +
   // Query database
   if (array_key_exists('pmtid', $payment) && !empty($payment['pmtid'])) {
       // Payment already exists, update

**Comment by chris18890** [comment]
see also #425
