### ISSUE TITLE
user_meta - user_meta_data_alter function was messing stuff up

### ISSUE THREAD

**Issue by davidbuzz** [elplatt/seltzer#212]
I just commented out the contents of the user_meta_data_alter function, and that seems to have fixed it.    ( I can still add/delete and edit meta data fine ) 

diff --git a/crm/modules/user_meta/user_meta.inc.php b/crm/modules/user_meta/user_meta.inc.php
index 501c166..ea1b557 100644
--- a/crm/modules/user_meta/user_meta.inc.php
+++ b/crm/modules/user_meta/user_meta.inc.php
@@ -244,7 +244,7 @@ function user_meta_data ($opts = array()) {
- @return An array of modified structures.
  */
  function user_meta_data_alter ($type, $data = array(), $opts = array()) {
  -    switch ($type) {
  -    /\* switch ($type) {
     case 'contact':
         // Get cids of all contacts passed into $data
         $cids = array();
    @@ -270,6 +270,7 @@ function user_meta_data_alter ($type, $data = array(), $opts = array()) {
         }
         break;
    }
  -    */
    return $data;
    }

**Comment by chris18890** [comment]
@davidbuzz  Is this still an issue? If not, can it be closed?

**Comment by davidbuzz** [comment]
no idea, we moved away from seltzer years ago.

**Comment by davidbuzz** [comment]
we use https://github.com/membermatters/MemberMatters now instead
