### ISSUE TITLE
give CSV exports more helpful names

### ISSUE THREAD

**Issue by myself248** [elplatt/seltzer#257]
Rather than export.csv from every tab, it would be helpful they had descriptive names, like keys.csv, members.csv, accounts.csv, etc.

**Comment by chris18890** [comment]
@myself248  IS this still an issue for you? I don't seem to have the option to export to CSV on the latest build

**Comment by myself248** [comment]
I have no idea why the option appears and disappears, but I have it right now, and it's giving sensible names.

**Comment by chris18890** [comment]
@myself248 do you know which branch you're running?

**Comment by myself248** [comment]
Bottom of the page says "Powered by i3 Detroit 0.5.5.dev"

**Comment by chris18890** [comment]
ok, that's wuite odd! do you know what fork you're running? cause if it's an issue with the original repo code then I can try to fix it

**Comment by elplatt** [comment]
@myself248 Sounds like your headers might be getting mangled somehow. I've been having that happen recently in other completely unrelated projects, but not sure why.

Also I believe i3 forked a while back, do you know who is most active with the Seltzer code right now? It would be great to spend a day getting things merged back together this summer.
