### ISSUE TITLE
change "method: cash" to something clearer

### ISSUE THREAD

**Issue by myself248** [elplatt/seltzer#262]
When billings run, and the CRM becomes aware of the passage of a month's time, and everyone's account indicates the movement of money out of it, the word "cash" is the most confusing way to indicate that. No dollar bills moved in or out of anything during this process, and most specifically, the member did not move any dollar bills anywhere. 

Crucially, someone who has *not been paying* for months should not be able to log into their account, look at their record, and see a "cash" entry month after month. You can't fix stupid, but you can try not to invite it so warmly.

I would suggest a term like "method: dues" or "method: deducted" or something, showing that this is absolutely NOT money being applied to their account, but money being CHARGED AGAINST IT. Gaaaaaaah. This is so mindbogglingly frustratingly confusingly represented. I'm sorry I just have to write this down and see if I'm the only one perplexed by this terminology.

**Comment by chris18890** [comment]
this issue can now be closed as it was fixed in #343
