### ISSUE TITLE
Payments tab has "credit" and "debit" columns but only uses one

### ISSUE THREAD

**Issue by myself248** [elplatt/seltzer#263]
Perhaps I misunderstand the terms, but isn't a negative number in the "credit" column the same as putting a positive number in the "debit" column?

**Comment by ramgarden** [comment]
I understood the Credit and Debit columns as a way for one member to pay for another member's dues by crediting one person and debiting the other.  If this is correct then does that mean we can close this issue?

**Comment by elplatt** [comment]
Josh, that's right. Can I close this from my email? Let's see. Close #263.

On Wed, May 20, 2015 at 4:07 PM, Josh P <notifications@github.com> wrote:

> I understood the Credit and Debit columns as a way for one member to pay
> for another member's dues by crediting one person and debiting the other.
> If this is correct then does that mean we can close this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elplatt/seltzer/issues/263#issuecomment-104020211>.
>



-- 
Edward L. Platt
http://elplatt.com
http://civic.mit.edu/users/elplatt
http://i3detroit.com
@elplatt <http://twitter.com/elplatt>

This electronic mail message was sent from my desktop personal computer.
Please forgive any long-winded, overly-prosaic ramblings.

**Comment by elplatt** [comment]
Closing.
