### ISSUE TITLE
PHP Warning on mysql_real_escape_string() function call in user_meta.inc.php

### ISSUE THREAD

**Issue by mattoehrlein** [elplatt/seltzer#286]
Came across this php warning in the user_meta module

[Sat Mar 29 20:59:33 2014] [error] [client 68.43.65.93] PHP Warning:  mysql_real_escape_string() expects parameter 1 to be string, array given in /home/matt/seltzer/crm/modules/user_meta/user_meta.inc.php on line 186, referer: http://seltzercrm.org/~matt/crm/?q=members

**Comment by chris18890** [comment]
Can't find the line that this refers to, comment referrs to old mysql_ api
