### ISSUE TITLE
Calendar and name completion pop up don't appear

### ISSUE THREAD

**Issue by Skellybat** [elplatt/seltzer#336]
This is on i3 Detroit instance. When selected the date of a membership plan starting or ending, or when their key has started or ended, the calendar no longer pops up. The date then has to be manually put in. The bigger issue is that when you go to type someone's name say in the credit cell in the payments tab, thier name does not come up. This is an issue, because I don't feel you can manually put in the name and have it link with the acount.

**Comment by chris18890** [comment]
happy for this to be closed now @elplatt as fixed by #359
