### ISSUE TITLE
No such command: amazon_payment_contact_delete

### ISSUE THREAD

**Issue by mjgardes** [elplatt/seltzer#346]
We can't really prevent members from switching Amazon accounts, so we need a way to delete the old association when they switch and tie their account with the new Amazon name.  For now I'm editing the database manually.  It's not currently possible to connect more than one Amazon name to an account.  

Additionally, clicking the "delete" button (why does it show up if there's no code for it yet?) gives the user a scare when it warns you it's going to delete someone else's Amazon name connection, in addition to the warning having the title "Delete Paypal Contact"

**Comment by elplatt** [comment]
Hey @chris18890, you've worked on the delete functionality, right? Any ideas?

**Comment by chris18890** [comment]
What version are you running @mjgardes? I've had a look at the dev branch & the delete functionality for amazon contacts is definitely there, you should be able to just delete the entry & add a new one, or add a new name with the same member, as the primary key on the database (in the dev branch) is amazon_name, so as long as it's unique the same member could have multiple entries.

**Comment by mjgardes** [comment]
I just cloned the database and ran it in a copy of the dev branch, and yes,
it does delete entries, however it deletes the wrong entry.  It removes the
top entry from the table not the selected one.

**Comment by mjgardes** [comment]
https://github.com/mjgardes/seltzer/commit/f200bc4df9c2c978a46e0b07a46be970ef9f4dcb

The amazon table needs to be filtered by amazon_name and not cid.

**Comment by chris18890** [comment]
@mjgardes ok, I'll see about getting this integrated! :)
