### ISSUE TITLE
when using Edit on a member record, boxes not prefilled with current data

### ISSUE THREAD

**Issue by myself248** [elplatt/seltzer#351]
i3detroit's instance, when going to edit a member record, the text boxes come up blank rather than having the current field data prefilled into them. 

@mjgardes speculated this might be related to another change recently made, so, tag, you're it! This bug is just for tracking at the moment, since I don't have any other info to contribute.

**Comment by chris18890** [comment]
hey @myself248 @mjgardes have you any more info on this bug?

**Comment by chris18890** [comment]
hey @myself248 @mjgardes is this still an issue?

**Comment by myself248** [comment]
I can't reproduce it, and I have no idea when it came good, but it's fine now.
