### ISSUE TITLE
Add fields for mailing address

### ISSUE THREAD

**Issue by myself248** [elplatt/seltzer#352]
If we're using Seltzer as our "membership book" for legal reasons, it's probably good for it to contain the data that a membership book is supposed to contain...

**Comment by chris18890** [comment]
This is tricky but do-able; When I did some mods to add extra stuff I did it in the membership module, to keep the contact module as (c)lean as possible - IMHO the "emergency contacts" shouldn't even be in contact, but member...

**Comment by chris18890** [comment]
@myself248 would the user meta module in release 0.5.0 be of use? #361 has also now happened, meaning that if you wantyed to hack member it's significantly easier to do so :)
