### ISSUE TITLE
Plan end dates

### ISSUE THREAD

**Issue by keithellis74** [elplatt/seltzer#354]
If a plan end date is set in advance, for example if a member signs up for one year, it is useful to pre-populate the end date so that when that date is reached the member will appear in the Lapsed email report.  However, as soon as any date is entered into the plan end date field that member immediately appears in the Lapsed email report.  Can this be changed so the user only appears in the Lapsed email report if the plan end date has passed.  Thank you.

**Comment by ramgarden** [comment]
This would be an easy fix if it really is just checking if the member's assigned plan end date is just not null vs an actual date check.

**Comment by elplatt** [comment]
Yep, I think it's just fixing a few places where it checks for null end
date to determine if a member is active. Adding an OR end date < now should
do it.

On Fri, Oct 30, 2015 at 10:32 AM, Josh P <notifications@github.com> wrote:

> This would be an easy fix if it really is just checking if the member's
> assigned plan end date is just not null vs an actual date check.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elplatt/seltzer/issues/354#issuecomment-152541604>.
>



-- 
Edward L. Platt
PhD student, University of Michigan School of Information
https://elplatt.com
@elplatt <http://twitter.com/elplatt>
KC1DYK

Tips for stopping email overload:
https://hbr.org/2012/02/stop-email-overload-1

This digital electronic mail message was sent from my general-purpose
desktop personal computing machine.  Please forgive any overly-verbose,
long-winded, rambling prose.

**Comment by ramgarden** [comment]
Wouldn't it be, to determine if a member is ACTIVE, be:
if plan end date is null OR end date > (greater than) now?  To say that the end date is further down the road than today?

**Comment by elplatt** [comment]
Right you are!

**Comment by keithellis74** [comment]
Another consequence of this issue is in the members list, the membership plan is not shown.(is is blank) and when filtering by Active or Voting the members are not shown.

**Comment by chris18890** [comment]
@elplatt feel free to assign this to me & I'll have a look at it over the weekend/next week :)

**Comment by ramgarden** [comment]
I'm about to fix this if no one else is working on it.  Let me know!

**Comment by elplatt** [comment]
As far as I know, no one else is working on it. I'll accept pull requests
for bug fixes as long as someone (other than the author) reviews and leaves
a comment saying it looks good.

On Sun, Nov 29, 2015 at 1:44 PM, Josh P <notifications@github.com> wrote:

> I'm about to fix this if no one else is working on it. Let me know!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elplatt/seltzer/issues/354#issuecomment-160446709>.
>



-- 
Edward L. Platt
PhD student, University of Michigan School of Information
https://elplatt.com
@elplatt <http://twitter.com/elplatt>
KC1DYK

Tips for stopping email overload:
https://hbr.org/2012/02/stop-email-overload-1

This digital electronic mail message was sent from my general-purpose
desktop personal computing machine.  Please forgive any overly-verbose,
long-winded, rambling prose.

**Comment by chris18890** [comment]
@elplatt in that case there's a few PRs in the queue that need reviewed... :P

**Comment by ramgarden** [comment]
OK, @chris18890 check if my /modules/member/data.inc.php looks good in my PR.  I tested it OK in my production install by changing my own membership end date to something in the future and I still showed up in the active report.  Set it to something in the past and showed up in the lapsed report.  Set it to null and showed up as active.

**Comment by chris18890** [comment]
commented in the PR @ramgarden  @elplatt

**Comment by chris18890** [comment]
happy for this to be closed @elplatt as fixed by #360

**Comment by keithellis74** [comment]
Thanks all.

Keith Ellis

**Comment by keithellis74** [comment]
Just one final comment, I not this fix it in the dev branch, Is there a plan to merge this with the master branch?  
Is the dev branch suitable for deployment?

**Comment by elplatt** [comment]
Dev branch is an at-your-own-risk thing, but some groups are using it.

**Comment by elplatt** [comment]
Also, the project is in maintenance only right now, so there won't be any new releases to master for a while.

**Comment by chris18890** [comment]
@Keithellis74 I've no idea about when it'll be deployed to master, @elplatt will make that decision, but I've found that the Dev branch is stable enough to deploy & use in production for @FarsetLabs
