### ISSUE TITLE
Adding new member throws "Duplicate Entry for Key PRIMARY" SQL error

### ISSUE THREAD

**Issue by ramgarden** [elplatt/seltzer#374]
After filling out the First Name, Last Name, Email, Phone number, emergency contact, and emergency phone fields then clicking the Add button it correctly saves the user and their info and their membership into the user_role table, but it throws this error and never gets to the step where it emails the admin user and the new user like it used to.  I've checked the line 120 in the /crm/modules/member/command.inc.php file and that's where it inserts the row into the user_role table and checks for SQL errors.  I looked in the DB before creating the new user and see that the last entry was 80-2 for example then add a new user and it throws error saying 81-2 is a duplicate entry.  I then refresh the view on the user_role table and just see the one new entry for 81-2.  It's almost like it's going into this piece of code twice or trying to save to the table twice?  It doesn't make sense that it would hit this same piece of code twice since it never sends the emails.  So it's like it's saving to the user_role table somewhere else first, then hitting this line in this section of code and throwing the error.
`
    Duplicate entry '82-2' for key 'PRIMARY'Array
    (
    [0] => Array
        (
            [file] => /home/content/s/a/i/username/html/webusername/crm/modules/member/command.inc.php
            [line] => 120
            [function] => crm_error
            [args] => Array
                (
                    [0] => Duplicate entry '82-2' for key 'PRIMARY'
                )

```
    )

[1] => Array
    (
        [function] => command_member_add
        [args] => Array
            (
            )

    )

[2] => Array
    (
        [file] => /home/content/s/a/i/username/html/webusername/crm/include/sys/command.inc.php
        [line] => 36
        [function] => call_user_func
        [args] => Array
            (
                [0] => command_member_add
            )

    )

[3] => Array
    (
        [file] => /home/content/s/a/i/username/html/webusername/crm/index.php
        [line] => 36
        [function] => command
        [args] => Array
            (
                [0] => member_add
            )

    )

)
```

`

**Comment by chris18890** [comment]
@ramgarden what branch are you using?

**Comment by ramgarden** [comment]
I don't remember.  Any way to find out?  Someone else actually "installed" it on our godaddy webserver host.

**Comment by ramgarden** [comment]
I'm pretty sure it was the master branch.  The other guy wouldn't know how to pull anything else down from here as a zip file.  Since it defaults to the master branch I'm sure that's what he pulled down.

**Comment by chris18890** [comment]
a quick way to find out is to look at the bottom of the page., if it just says "Powered by Seltzer CRM ' it's master, but if it says "Powered by Seltzer CRM" with a version number (likely to be 0.4.3) it's the dev branch

**Comment by ramgarden** [comment]
Yep. No verson number. So it must be master.

**Comment by chris18890** [comment]
If you can move to the dev branch I think most of these issues are sorted there, & once @elplatt merges some of the open pull requests few other bugs will be tidied up too

**Comment by ramgarden** [comment]
I'm afraid to make a big change like that since our front door lock relies on the DB behind Seltzer.  By "moving" to the dev branch do you mean just downloading that zip and replacing all the php files on the webserver with those?  Does it make any changes to the DB the first time it would connect to the DB once the config file was changed to point to our DB/user/password/etc?

**Comment by chris18890** [comment]
well, that's part of it, you may also need to upgrade the database, I'll need to check to see what differences there are between dev & master

**Comment by ramgarden** [comment]
So I just found where the issue arises and "fixed it" but I need you all to look at it further.
The problem comes when in modules/member/command.inc.php line 119 when it tries to INSERT INTO user_role table as a "member" role and that row already exists.  So it's either hitting the same line of code twice or it's inserting into the user_role table somewhere else first before it gets here - such as when it calls contact_save() on line 103?
I just commented out line 120 in command.inc.php so it wouldn't call crm_error and continue even if there was an error inserting that duplicate row and now it sends the emails as it should just fine.
Can anyone else find where it might be inserting this row twice or calling this same code twice?

**Comment by chris18890** [comment]
ah, ok, thanks! I'll look at getting this pushed into the latest dev build & pinging @elplatt to approve recent pull requests :)

**Comment by chris18890** [comment]
@ramgarden is this still an outstanding issue?

**Comment by ramgarden** [comment]
I haven't put in a code fix for it yet.  I still have that line commented out on our copy of the code on our server.  Did you ever fix that line of code?  Does it not happen to anyone else?

**Comment by chris18890** [comment]
if you're still running code from the master branch, it probably hasn't been fixed, as the line numbers you reference don't point to that when I look at the file on the dev branch!  The old code was calling a lot of different user setup bits in different places; I did a lot of refactoring & the issue has been fixed in the dev branch for some time now, but there is a version jump for some of the modules & a DB upgrade needed

**Comment by chris18890** [comment]
@ramgarden are you happy that this is closed due to the issue being sorted in dev, & the master branch soon to be updated with a new release?

**Comment by ramgarden** [comment]
I'm assuming you've tested this on a test machine and it works OK?  If so, then yes.

**Comment by chris18890** [comment]
yes, this has been tested & adding new members works well on both current master & dev branches. closing :)

**Comment by chris18890** [comment]
@ramgarden would be happy to take this to email/other comms if you wanted to have a proper chat & possibly migrate  your install to the latest version of dev/master :)
