### ISSUE TITLE
Profile Picture module allows any user to change any other user's photo

### ISSUE THREAD

**Issue by ramgarden** [elplatt/seltzer#376]
It should only allow the currently logged in user to change their own photo and no one else - but still view other member's photos.  Unless the user has contact_edit permission.
NOTE: I've already fixed this issue in profile_picture.inc.php.
//only allow users to upload photos for their OWN profile!
// OR if they have contact_edit permission.
if ($cid == user_id() || user_access('contact_edit'))
{
	$view_content .= theme('form', crm_get_form('profile_picture_upload',  $cid));
}

**Comment by chris18890** [comment]
@ramgarden I assume this can be closed now?

**Comment by ramgarden** [comment]
Yep!  I'll close it now since the code has been merged and tested OK!
