### ISSUE TITLE
error process billing, and saving payments 

### ISSUE THREAD

**Issue by tlanelabs** [elplatt/seltzer#425]
Just did a fresh install and I'm getting the following errors when trying to save a payment or process billing. 
Any thoughts?

`Array
(
    [0] => Array
        (
            [file] => /var/www/html/crm/modules/payment/payment.inc.php
            [line] => 463
            [function] => crm_error
            [args] => Array
                (
                    [0] => 
                )

        )

    [1] => Array
        (
            [file] => /var/www/html/crm/modules/billing/billing.inc.php
            [line] => 295
            [function] => payment_save
            [args] => Array
                (
                    [0] => Array
                        (
                            [date] => 2019-03-03
                            [description] => Dues: test
                            [code] => USD
                            [value] => -1122
                            [credit_cid] => 2
                            [method] => 
                        )

                )

        )

    [2] => Array
        (
            [file] => /var/www/html/crm/modules/billing/billing.inc.php
            [line] => 162
            [function] => billing_bill_membership
            [args] => Array
                (
                    [0] => Array
                        (
                            [cid] => 2
                            [sid] => 1
                            [pid] => 1
                            [start] => 2019-03-03
                            [end] => 
                            [plan] => Array
                                (
                                    [pid] => 1
                                    [name] => test
                                    [price] => 12
                                    [active] => 1
                                    [voting] => 0
                                )

                        )

                    [1] => 2019-03-03
                    [2] => 
                )

        )

    [3] => Array
        (
            [file] => /var/www/html/crm/include/sys/command.inc.php
            [line] => 37
            [function] => command_billing
            [args] => Array
                (
                )

        )

    [4] => Array
        (
            [file] => /var/www/html/crm/index.php
            [line] => 36
            [function] => command
            [args] => Array
                (
                    [0] => billing
                )

        )

)`

**Comment by chris18890** [comment]
Hey @tlanelabs! Tah for flagging this up, I’ll try to have a look at it this week :)

**Comment by elplatt** [comment]
Hi @tlanelabs ! If you haven't already, please add yourself to the following list so we can know more about who is using seltzer and for what: https://goo.gl/forms/XVCEvZukoDADF0e42

**Comment by chris18890** [comment]
@tlanelabs which branch are you using?

**Comment by tlanelabs** [comment]
Hey @chris18890  sorry for the late reply. Currently I have 0.5.6.dev runing. but I also tried the master with the same results.

**Comment by chris18890** [comment]
@tlanelabs no worries :) Have you created all your plans & users (& made sure your users all have plans assigned) first? I'll spin up a test instance this evening & see if I can replicate the issue :)

**Comment by tlanelabs** [comment]
I just made one of each to test it out.

**Comment by chris18890** [comment]
Sorry for the delayed response on this

The good(?) news is that I've been able to reproduce it in dev & master, so now I just need to figure out what's caused it!

**Comment by tlanelabs** [comment]
No rush. We still haven't launched our makerspace yet, but this software looks promising. Looking forward to implementing it.

**Comment by ramgarden** [comment]
@tlanelabs we've been using Seltzer as our main member database and payment tracking database for about 3 almost 4 years now.  We even built our front door lock to use RFID tags/cards and query the Seltzer DB with their key to make sure they aren't more than 2 months over due.  So it will automatically lock them out if they haven't paid their dues just by our treasurer running the billing process and importing our PayPal payments each month.  If you want to build your own version of the front door lock like other makerspaces have the info is here: https://wiki.melbournemakerspace.org/projects/RFIDDoorLock

**Comment by chris18890** [comment]
looks like it's a SQL issue that I've come across before as well, the payment_save function didn't like that (when running billing the credit_cid) credit_cid & debit_cid fields were empty. I figured this out cuase I couldn't import paypal payments or even add a signle payment manually, all were failing with the same issue. I've opened #427 for review

**Comment by chris18890** [comment]
see also #211
