### ISSUE TITLE
incompatability with PHP 8.*

### ISSUE THREAD

**Issue by chris18890** [elplatt/seltzer#527]
Alongside #506 & #511, due to changes in PHP from 7.4 > 8.*, reports & paypal contacts are causing errors
* getting a "cannot access offset of type string on string" error when trying to access paypal contacts
* getting a "argument must be of type array string given" error when trying to access reports

happy for any/all help on this one @drid @ramgarden!

**Comment by joshprittse** [comment]
That offset error _might_ be related to how the paypal CSV file/export file has a UTF-8 character (BOM?) at the end that needs to be shaved off.

**Comment by chris18890** [comment]
Unfortunately I don't think so, cause the Paypal CSV relates to the payments, this is related to the paypal contacts, which are creates when creating a new member.

I've tested importing members from CSV & also creating a new single member, both result in the same error, so I think it's how paypal_contact_data is getting emails, and/or how paypal_contact_table is displaying them
